# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  twmailer_server_config = debug
  twmailer_client_config = debug
endif
ifeq ($(config),release)
  twmailer_server_config = release
  twmailer_client_config = release
endif
ifeq ($(config),dist)
  twmailer_server_config = dist
  twmailer_client_config = dist
endif

PROJECTS := twmailer-server twmailer-client

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

twmailer-server:
ifneq (,$(twmailer_server_config))
	@echo "==== Building twmailer-server ($(twmailer_server_config)) ===="
	@${MAKE} --no-print-directory -C twmailer-server -f Makefile config=$(twmailer_server_config)
endif

twmailer-client:
ifneq (,$(twmailer_client_config))
	@echo "==== Building twmailer-client ($(twmailer_client_config)) ===="
	@${MAKE} --no-print-directory -C twmailer-client -f Makefile config=$(twmailer_client_config)
endif

clean:
	@${MAKE} --no-print-directory -C twmailer-server -f Makefile clean
	@${MAKE} --no-print-directory -C twmailer-client -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   twmailer-server"
	@echo "   twmailer-client"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"